joint_names: [joint1, joint2,joint3,joint4]

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## velocity controller
joint1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint1
  pid: {p: 3.0, i: 0.0, d: 0.0}
  required_drive_mode: 3

joint2_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint2
  pid: {p: 3.0, i: 0.0, d: 0.0}
  required_drive_mode: 3

joint3_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint3
  pid: {p: 3.0, i: 0.0, d: 0.0}
  required_drive_mode: 3

joint4_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint4
  pid: {p: 3.0, i: 0.0, d: 0.0}
  required_drive_mode: 3
